#######################################################################################
# Book settings
title: Quantitative Investing
author: Alan Moreira
email: ''
logo                        : "figuremain2.jpg"  # A path to the book logo
exclude_patterns            : ["README.md"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
copyright                   : "2021 Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)"
#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "figuremain2.jpg"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://amoreira2.github.io/quantitativeinvesting/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface:        "jupyterlab"
  jupyterhub_url            : "https://pims.syzygy.ca/jupyter"
  colab_url              : "https://colab.research.google.com" # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/amoreira2/Lectures  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links

sphinx:
  config:
    html_extra_path: ['assets']

theme: jekyll-theme-cayman